/// This file aims to make a better experience for end users by mapping proto::* classes into
/// a user friendly Rpc::* enum and have better documentation

/// Requests, these are made by the end user and will all normally recieve an RpcResponse
pub enum RpcRequest {
    StopSession(super::StopSession),
    SystemPingRequest(super::super::system::PingRequest),
    SystemRebootRequest(super::super::system::RebootRequest),
    SystemDeviceInfoRequest(super::super::system::DeviceInfoRequest),
    SystemFactoryResetRequest(super::super::system::FactoryResetRequest),
    SystemGetDatetimeRequest(super::super::system::GetDateTimeRequest),
    SystemSetDatetimeRequest(super::super::system::SetDateTimeRequest),
    SystemPlayAudiovisualAlertRequest(super::super::system::PlayAudiovisualAlertRequest),
    SystemProtobufVersionRequest(super::super::system::ProtobufVersionRequest),
    SystemUpdateRequest(super::super::system::UpdateRequest),
    SystemPowerInfoRequest(super::super::system::PowerInfoRequest),
    StorageInfoRequest(super::super::storage::InfoRequest),
    StorageTimestampRequest(super::super::storage::TimestampRequest),
    StorageStatRequest(super::super::storage::StatRequest),
    StorageListRequest(super::super::storage::ListRequest),
    StorageReadRequest(super::super::storage::ReadRequest),
    StorageWriteRequest(super::super::storage::WriteRequest),
    StorageDeleteRequest(super::super::storage::DeleteRequest),
    StorageMkdirRequest(super::super::storage::MkdirRequest),
    StorageMd5sumRequest(super::super::storage::Md5sumRequest),
    StorageRenameRequest(super::super::storage::RenameRequest),
    StorageBackupCreateRequest(super::super::storage::BackupCreateRequest),
    StorageBackupRestoreRequest(super::super::storage::BackupRestoreRequest),
    StorageTarExtractRequest(super::super::storage::TarExtractRequest),
    AppStartRequest(super::super::app::StartRequest),
    AppLockStatusRequest(super::super::app::LockStatusRequest),
    AppExitRequest(super::super::app::AppExitRequest),
    AppLoadFileRequest(super::super::app::AppLoadFileRequest),
    AppButtonPressRequest(super::super::app::AppButtonPressRequest),
    AppButtonReleaseRequest(super::super::app::AppButtonReleaseRequest),
    AppButtonPressReleaseRequest(super::super::app::AppButtonPressReleaseRequest),
    AppGetErrorRequest(super::super::app::GetErrorRequest),
    AppDataExchangeRequest(super::super::app::DataExchangeRequest),
    GuiStartScreenStreamRequest(super::super::gui::StartScreenStreamRequest),
    GuiStopScreenStreamRequest(super::super::gui::StopScreenStreamRequest),
    GuiSendInputEventRequest(super::super::gui::SendInputEventRequest),
    GuiStartVirtualDisplayRequest(super::super::gui::StartVirtualDisplayRequest),
    GuiStopVirtualDisplayRequest(super::super::gui::StopVirtualDisplayRequest),
    GpioSetPinMode(super::super::gpio::SetPinMode),
    GpioSetInputPull(super::super::gpio::SetInputPull),
    GpioGetPinMode(super::super::gpio::GetPinMode),
    GpioReadPin(super::super::gpio::ReadPin),
    GpioWritePin(super::super::gpio::WritePin),
    GpioGetOtgMode(super::super::gpio::GetOtgMode),
    GpioSetOtgMode(super::super::gpio::SetOtgMode),
    PropertyGetRequest(super::super::property::GetRequest),
    DesktopIsLockedRequest(super::super::desktop::IsLockedRequest),
    DesktopUnlockRequest(super::super::desktop::UnlockRequest),
    DesktopStatusSubscribeRequest(super::super::desktop::StatusSubscribeRequest),
    DesktopStatusUnsubscribeRequest(super::super::desktop::StatusUnsubscribeRequest),
}

/// Reponse from flipper
pub enum RpcResponse {
    Empty,
    SystemPingResponse(super::super::system::PingResponse),
    SystemDeviceInfoResponse(super::super::system::DeviceInfoResponse),
    SystemGetDatetimeResponse(super::super::system::GetDateTimeResponse),
    SystemProtobufVersionResponse(super::super::system::ProtobufVersionResponse),
    SystemUpdateResponse(super::super::system::UpdateResponse),
    SystemPowerInfoResponse(super::super::system::PowerInfoResponse),
    StorageInfoResponse(super::super::storage::InfoResponse),
    StorageTimestampResponse(super::super::storage::TimestampResponse),
    StorageStatResponse(super::super::storage::StatResponse),
    StorageListResponse(super::super::storage::ListResponse),
    StorageReadResponse(super::super::storage::ReadResponse),
    StorageMd5sumResponse(super::super::storage::Md5sumResponse),
    AppLockStatusResponse(super::super::app::LockStatusResponse),
    AppGetErrorResponse(super::super::app::GetErrorResponse),
    GuiScreenFrame(super::super::gui::ScreenFrame),
    GpioGetPinModeResponse(super::super::gpio::GetPinModeResponse),
    GpioReadPinResponse(super::super::gpio::ReadPinResponse),
    GpioGetOtgModeResponse(super::super::gpio::GetOtgModeResponse),
    AppStateResponse(super::super::app::AppStateResponse),
    PropertyGetResponse(super::super::property::GetResponse),
    DesktopStatus(super::super::desktop::Status),
}
